// CMake autogenerated header file

#define LD_API_URL "https://discordapp.com/api"
#define LD_LIB_VER ""
#define LD_SYSTEMOS "Linux 5.8.0-44-generic"

#define LD_REST_API_VERSION "/v6"
#define LD_WS_API_VERSION 6
#define LD_GATEWAY_API_VERSION 
#define LD_VERSION "0.3"
#define LD_GITHUB_URL "https://github.com/dxing97/libdiscord"
#define LD_LIBNAME "libdiscord"

#define LD_RINGBUFFER_DEFAULT_SIZE 16
#define LD_CONNECT_DELAY_INTERVAL 5
